//
//  ListaFilmesInteractorTests.swift
//  TesteSky
//
//  Created by Julio Cezar de Souza on 25/06/20.
//  Copyright (c) 2020 Julio Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TesteSky
import XCTest

class ListaFilmesInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ListaFilmesInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupListaFilmesInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupListaFilmesInteractor() {
        sut = ListaFilmesInteractor()
    }
    
    // MARK: Test doubles
    
    class ListaFilmesPresentationLogicSpy: ListaFilmesPresentationLogic {
        
        var chamouPresentList = false
        var chamouError = false
        
        func presentList(response: ListaFilmes.Response) {
            chamouPresentList = true
        }
        
        func presentDefaultError() {
            chamouError = true
        }
    }
    
        // MARK: Tests
    
        func carregarListaInicialFilmes() {
            // Given
            let spy = ListaFilmesPresentationLogicSpy()
            sut.presenter = spy
//            let request = ListaFilmes.Request(service: .get)
    
            // When
            sut.carregarListaInicialFilmes()
    
            // Then
            XCTAssertTrue(spy.chamouPresentList, "interactor recebeu dado e esta mandando para a presenter")
        }
}
