//
//  ListaFilmesPresenterTests.swift
//  TesteSky
//
//  Created by Julio Cezar de Souza on 25/06/20.
//  Copyright (c) 2020 Julio Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TesteSky
import XCTest

class ListaFilmesPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListaFilmesPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListaFilmesPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListaFilmesPresenter()
  {
    sut = ListaFilmesPresenter()
  }
  
  // MARK: Test doubles
  
  class ListaFilmesDisplayLogicSpy: ListaFilmesDisplayLogic {
    var chamouListaFilmes = false
    
    func exibirListaFilmes(response: ListaFilmes.Response) {
        chamouListaFilmes = true
    }
  }
//  
  // MARK: Tests
  
  func presentList() {
    // Given
    let spy = ListaFilmesDisplayLogicSpy()
    sut.viewController = spy
    let response = ListaFilmes.Response()
    
    // When
    sut.presentList(response: response)
    // Then
    XCTAssertTrue(spy.chamouListaFilmes, "A presenter passou os dados para controller")
  }
}
