//
//  ListaFilmesWorker.swift
//  TesteSky
//
//  Created by Julio Cezar de Souza on 22/06/20.
//  Copyright (c) 2020 Julio Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  Users/cezar/Documentos/TesteSky/TesteSky/Scenes/Listagem/ListaFilmesWorker.swift
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListaFilmesWorker: APIClient {

    var session: URLSession
    
    init(configuration: URLSessionConfiguration) {
        self.session = URLSession(configuration: configuration)
    }
    
    convenience init() {
        self.init(configuration: .default)
    }
    
    func getListaFilmes(request: ListaFilmes.Request, completion: @escaping (Result<ListaFilmes.Response?, APIError>) -> Void) {
        let endpoint = request.service
        var request = endpoint.request
        request.url = URL(string: request.url!.absoluteString.removingPercentEncoding!)
        request.httpMethod = "get"
        print("abriu worker")
        fetch(with: request, decode: { json -> ListaFilmes.Response? in
            guard let feedResult = json as? ListaFilmes.Response else {
                print("retornou nada")
                return  nil }
            print("retornou worker")
            return feedResult
        }, completion: completion)
    }
    
}
