//
//  ListaFilmesInteractor.swift
//  TesteSky
//
//  Created by Julio Cezar de Souza on 22/06/20.
//  Copyright (c) 2020 Julio Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListaFilmesBusinessLogic {
    func carregarListaInicialFilmes()
}

protocol ListaFilmesDataStore {
  //var name: String { get set }
}

class ListaFilmesInteractor: ListaFilmesBusinessLogic, ListaFilmesDataStore
{
  
    var presenter: ListaFilmesPresentationLogic?
    var worker: ListaFilmesWorker?

    func carregarListaInicialFilmes() {
        
        let request = ListaFilmes.Request(service: .get)
        
        worker?.getListaFilmes(request: request, completion: { (result) in
            switch result {
            case .success(let response):
                guard let resp = response else {
                    print("response nil")
                    self.presenter?.presentDefaultError()
                    return }
                self.presenter?.presentList(response: resp)
            case .failure(let error):
                print(error.localizedDescription)
                self.presenter?.presentDefaultError()
            }
        })
        
    }

}
