//
//  DetalheInteractor.swift
//  TesteSky
//
//  Created by Julio Cezar de Souza on 24/06/20.
//  Copyright (c) 2020 Julio Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetalheBusinessLogic
{
  func doSomething(request: Detalhe.Something.Request)
}

protocol DetalheDataStore
{
  //var name: String { get set }
}

class DetalheInteractor: DetalheBusinessLogic, DetalheDataStore
{
  var presenter: DetalhePresentationLogic?
  var worker: DetalheWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Detalhe.Something.Request)
  {
    worker = DetalheWorker()
    worker?.doSomeWork()
    
    let response = Detalhe.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
